name: Compile Rhythms
on:
  push:
    paths:
      - 'rhythms/**'
      - '!rhythms/README.md'
  pull_request:
    paths:
      - 'rhythms/**'
      - '!rhythms/README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 24.x
    - run: npm ci && npm run rhythms
